In [36]:
from sklearn.datasets import load_digits, load_wine, load_breast_cancer
digits_dataset = load_digits()
wine_dataset = load_wine()
cancer_dataset = load_breast_cancer()
print("Ключи Digits_dataset: \n{}".format(digits_dataset.keys()))
print("Ключи Wine_dataset: \n{}".format(wine_dataset.keys()))
print("Ключи Cancer_dataset: \n{}".format(cancer_dataset.keys()))

Ключи Digits_dataset: 
dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])
Ключи Wine_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])
Ключи Cancer_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
print(digits_dataset['DESCR'][:1000] + "\n...")

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 1797
:Number of Attributes: 64
:Attribute Information: 8x8 image of integer pixels in the range 0..16.
:Missing Attribute Values: None
:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
:Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an in

In [7]:
print(wine_dataset['DESCR'][:1000] + "\n...")

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

In [8]:
print(cancer_dataset['DESCR'][:1000] + "\n...")

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [9]:
print(digits_dataset['data'])

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [10]:
print(wine_dataset['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [11]:
print(cancer_dataset['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [14]:
from sklearn.model_selection import train_test_split
X_train_dig, X_test_dig, y_train_dig, y_test_dig = train_test_split(digits_dataset['data'], digits_dataset['target'], random_state=0)

In [15]:
print("Форма массива X_train_dig: {}".format(X_train_dig.shape))
print("Форма массива y_traing_dig: {}".format(y_train_dig.shape))

Форма массива X_train_dig: (1347, 64)
Форма массива y_traing_dig: (1347,)


In [16]:
print("Форма массива X_test_dig: {}".format(X_test_dig.shape))
print("Форма массива y_test_dig: {}".format(y_test_dig.shape))

Форма массива X_test_dig: (450, 64)
Форма массива y_test_dig: (450,)


In [17]:
from sklearn.model_selection import train_test_split
X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(wine_dataset['data'], wine_dataset['target'], random_state=0)

In [18]:
print("Форма массива X_train_wine: {}".format(X_train_wine.shape))
print("Форма массива y_traing_wine: {}".format(y_train_wine.shape))

Форма массива X_train_wine: (133, 13)
Форма массива y_traing_wine: (133,)


In [19]:
print("Форма массива X_train_wine: {}".format(X_train_wine.shape))
print("Форма массива y_traing_wine: {}".format(y_train_wine.shape))

Форма массива X_test_wine: (45, 13)
Форма массива y_test_wine: (45,)


In [20]:
from sklearn.model_selection import train_test_split
X_train_can, X_test_can, y_train_can, y_test_can = train_test_split(cancer_dataset['data'], cancer_dataset['target'], random_state=0)

In [21]:
print("Форма массива X_train_can: {}".format(X_train_can.shape))
print("Форма массива y_train_can: {}".format(y_train_can.shape))

Форма массива X_train_can: (426, 30)
Форма массива y_traing_can: (426,)


In [23]:
print("Форма массива X_test_can: {}".format(X_test_can.shape))
print("Форма массива y_test_can: {}".format(y_test_can.shape))

Форма массива X_test_can: (143, 30)
Форма массива y_test_can: (143,)


In [ ]:
#создаем dataframe из данных в массиве X_train_dig
#Маркируем столбцы, используя строки в digits_dataset.feature_names
import pandas as pd
digits_dataframe = pd.DataFrame(X_train_dig, columns=digits_dataset.feature_names)
#Создаем матрицу рассеяния из dataframe, цвет точек задаем с помощью y_train_dig
grr_dig = pd.plotting.scatter_matrix(digits_dataframe, c = y_train_dig, figsize= (15, 15), marker = 'o', hist_kwds={'bins':20}, s=60, alpha=.8) 

In [26]:
# #создаем dataframe из данных в массиве X_train_dig
# #Маркируем столбцы, используя строки в digits_dataset.feature_names
# import pandas as pd
# digits_dataframe = pd.DataFrame(X_train_dig, columns=digits_dataset.feature_names)
# #Создаем матрицу рассеяния из dataframe, цвет точек задаем с помощью y_train_dig
# grr_dig = pd.plotting.scatter_matrix(digits_dataframe, c = y_train_dig, figsize= (15, 15), marker = 'o', hist_kwds={'bins':20}, s=60, alpha=.8)

In [27]:
# #создаем dataframe из данных в массиве X_train_dig
# #Маркируем столбцы, используя строки в digits_dataset.feature_names
# import pandas as pd
# digits_dataframe = pd.DataFrame(X_train_dig, columns=digits_dataset.feature_names)
# #Создаем матрицу рассеяния из dataframe, цвет точек задаем с помощью y_train_dig
# grr_dig = pd.plotting.scatter_matrix(digits_dataframe, c = y_train_dig, figsize= (15, 15), marker = 'o', hist_kwds={'bins':20}, s=60, alpha=.8)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)


In [31]:
knn.fit(X_train_dig, y_train_dig)
knn.fit(X_train_wine, y_train_wine)
knn.fit(X_train_can, y_train_can)

KNeighborsClassifier(n_neighbors=1)

In [39]:
import numpy as np
X_new_dig = np.array([[0.1, 0.1, 0.1, 0.1]])
print(X_new_dig.shape)

(1, 4)


In [40]:
prediction = knn.predict(X_new_dig)
print(prediction)
print(digits_dataset['target_names'][prediction])

ValueError: X has 4 features, but KNeighborsClassifier is expecting 30 features as input.